import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "@styles/tailwind.global.css";

const defaultFontFamily = Nunito({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${defaultFontFamily.className}  antialiased`}>
        {children}
      </body>
    </html>
  );
}
